id: AAC77F4DA
title: The Abbreviated Prayer in Seven Chapters
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:05:00.944327
  last_modified_at: 2022-03-01 01:05:00.944330
