id: AAC77F4DA
title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:05:00.940750
  last_modified_at: 2022-03-01 01:05:00.940760
